name: Build & Test
on: [pull_request, workflow_dispatch]
jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: bun install

      - name: Build
        env:
          SKIP_ENV_VALIDATION: true
        run: bun run build

      - name: Test
        run: bun test
